### ISSUE TITLE
[Bug]: PC端卡住之后打不开了……（重装重启都没用）附上日志

### ISSUE THREAD

**Issue by levi0014** [venera-app/venera#111]
### Description

日志名称:          Application
来源:            Application Error
日期:            2024/12/19 18:43:21
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺

描述:
错误应用程序名称: venera.exe，版本: 1.1.2.112，时间戳: 0x6762c2cc
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.4522，时间戳: 0xf7a99bd4
异常代码: 0xc0000602
错误偏移量: 0x000000000012d332
错误进程 ID: 0x4260
错误应用程序启动时间: 0x01db51fe6c414547
错误应用程序路径: C:\Program Files (x86)\Venera\venera.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 9a80dbe2-1ac6-4406-a7b3-f694fe684ea7
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-19T10:43:21.8934463Z" />
    <EventRecordID>18031354</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
  
    <Security />
  </System>
  <EventData>
    <Data>venera.exe</Data>
    <Data>1.1.2.112</Data>
    <Data>6762c2cc</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.4522</Data>
    <Data>f7a99bd4</Data>
    <Data>c0000602</Data>
    <Data>000000000012d332</Data>
    <Data>4260</Data>
    <Data>01db51fe6c414547</Data>
    <Data>C:\Program Files (x86)\Venera\venera.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>9a80dbe2-1ac6-4406-a7b3-f694fe684ea7</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

### Version

1.1.2.112

### Operating system

Windows

**Comment by wgh136** [comment]
试试清一下数据, 在`C:\Users\用户名\AppData\Roaming\com.github.wgh136\venera`

**Comment by levi0014** [comment]
thx，能打开了。

**Comment by wgh136** [comment]
无法确定问题, 如果有人遇到此问题, 希望能够发一下app数据, 压缩后上传到Github上就可以了

**Comment by levi0014** [comment]
> 无法确定问题, 如果有人遇到此问题, 希望能够发一下app数据, 压缩后上传到Github上就可以了

这是我清理之前的备份。
[问题数据备份.zip](https://github.com/user-attachments/files/18219116/default.zip)
[安装目录的data文件夹.zip](https://github.com/user-attachments/files/18219117/data.zip)

**Comment by wgh136** [comment]
产生问题的原因是`downloading_tasks.json`变成了空文件, 导致app读取数据失败, 将其删除后可以正常打开app
