### ISSUE TITLE
[Enhancement]: （可能算是订阅源问题）希望增加漫画章节列表分类分栏功能

### ISSUE THREAD

**Issue by Spark-Plug** [venera-app/venera#16]
### Description

（可能算是订阅源问题，不归这里的话我删掉哈）
比如拷贝漫画的源，在漫画章节区域有时会有web版，连载版，其他系列等特殊排版，但是目前只能读到最上面一个版面的内容。
![image](https://github.com/user-attachments/assets/c762d3b9-2b30-4e28-a4d5-06b351dee5e3)
![IMG_3059](https://github.com/user-attachments/assets/14f984f2-6f18-441b-a967-460e3775bccc)

### Operating System

iOS

**Comment by wgh136** [comment]
章节列表分类太少见了, 修改漫画源配置文件, 使其加载所有的分类然后放一起会比较好
