### ISSUE TITLE
[Bug]: connection error AlertReceived(HandshakeFailure)

### ISSUE THREAD

**Issue by boa-z** [venera-app/venera#27]
### Version

1.0.4

### Operating system

Android, iOS, Windows, macOS

### logs

```text
DioException [unknown]: null
Error: [RhttpConnectionException] Connection error. URL: https://iksrnhd.dfobqvyytozx.hath.network:65500/h/xxxx.jpg (hyper_util::client::legacy::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: AlertReceived(HandshakeFailure) } }))
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520)
<asynchronous suspension>
#1      ImageDownloader.loadComicImage (package:venera/network/images.dart:102)
<asynchronous suspension>
#2      _ImageDownloadWrapper.start (package:venera/network/download.dart:518)
<asynchronous suspension>
```

**Comment by wgh136** [comment]
This is a server-side issue.
ehentai provides an API called 'Reload broken image' which can provide a new image link. 
I think we need to add an 'onLoadFailed' API to solve this problem

**Comment by boa-z** [comment]
It seems that the new version ([926437b](https://github.com/venera-app/venera/commit/926437b9675a7efae317a1b7f3e2298a5038f0fe)) led to picacomic source’s new bug. The following error must occur until retry twice.

```text
GET https://picaapi.picacomic.com/users/favourite?page=1&s=dd
DioException [unknown]: null
Error: [RhttpConnectionException] Connection error. URL: https://picaapi.picacomic.com/users/favourite?page=1&s=dd (hyper_util::client::legacy::Error(Connect, Custom { kind: Other, error: Custom { kind: UnexpectedEof, error: "tls handshake eof" } }))
null
```

**Comment by boa-z** [comment]
I’ve tested several times on previous iOS version with same network. Could you provide the version which has worked fine?

**Comment by wgh136** [comment]
I don't think it is related to version, as I never encountered this error.

**Comment by Pacalini** [comment]
Some H@H node do not support TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by boa-z** [comment]
Since this is an issue related to a small number of servers, if everyone agrees that this does not need to be fixed, I will close this issue as "Not Planned".
