### ISSUE TITLE
[Enhancement]: 拉齐原有功能, 支持原有数据导入

### ISSUE THREAD

**Issue by luckyray-fan** [venera-app/venera#28]
### Description

希望大大可以加下以下的功能❤️:
- 图片收藏
- 下拉更新网络收藏到本地
- 原有导出数据可以导入, 包括不限于: 图片收藏, 历史阅读进度, 网络收藏和本地收藏的绑定关系(避免每次迁移都要重新从网络导入)

**Comment by wgh136** [comment]
图片收藏我不打算做，欢迎pr
