### ISSUE TITLE
[Enhancement]: 收藏页多选,移动 发现页下滑更新漫画,滑动一段距离后原刷新变为快速回顶

### ISSUE THREAD

**Issue by axlmly** [venera-app/venera#52]
### Description

收藏页增加长按多选漫画逻辑,并且实现选择一个目标后长按间隔n个目标的漫画后全部选中(或反选.
移动漫画从一个文件夹到另一个文件夹
发现页处于最顶端下滑一定距离触发刷新发现页.
发现页下滑一定距离能够快速回顶(mixed)

**Comment by wgh136** [comment]
@axlmly 好，你来做
