### ISSUE TITLE
[Bug]: Android上添加漫画源是选择使用配置文件提示Invaild file type

### ISSUE THREAD

**Issue by qiusunshine** [venera-app/venera#59]
### Description

选择的是js源文件，但还是提示Invaild file type

看了下代码应该是选择了文件又根据文件路径判断了文件后缀是不是js

而Android上使用SAF读取文件只能获取文件流，部分文件无法直接获取文件路径和文件名，因此报错

### Version

V1.0.6

### Operating system

Android

**Comment by wgh136** [comment]
@qiusunshine Android上使用SAF读取文件可以获取到完整的路径, 只是master分支的代码有点问题, 试试dev分支
