### ISSUE TITLE
[Bug]: 使用自签软件更新版本后白屏

### ISSUE THREAD

**Issue by dtdtbaka** [venera-app/venera#65]
### Description

使用一段时间后，使用自签软件更新版本。打开后白屏，回退版本后依然白屏。

### Version

1.0.6

### Operating system

iOS

### logs

白屏无法查看log

### Screenshot or video

![aaaaaa](https://github.com/user-attachments/assets/8dbce109-301c-40b0-add0-ee8b83fa1a40)

**Comment by boa-z** [comment]
签名工具使用问题，大概率不属于本软件bug，建议尝试重新安装

**Comment by dtdtbaka** [comment]
重装后可以正常使用，同版本覆盖安装后再次白屏

**Comment by boa-z** [comment]
> 猜测是覆盖安装导致app id改变，加载某些文件失败，如果ios默认将所有文件存在公用目录说不定能解决这个问题

确实有问题，我等会去看看
