### ISSUE TITLE
[Bug]: nhentai存在特殊符号的tag点击进入会存在错误

### ISSUE THREAD

**Issue by dtdtbaka** [venera-app/venera#74]
### Description

nhentai存在特殊符号的tag点击进入会存在错误

### Version

1.0.7

### Operating system

iOS

### logs

报错如下图

### Screenshot or video

![ec08950f2f99253df99ab831a52aab8](https://github.com/user-attachments/assets/60e1344d-2087-41fb-8a19-67fbfd4d9d4c)

**Comment by wgh136** [comment]
发错地方了
