### ISSUE TITLE
[Bug]: nhentai标题选择出现问题

### ISSUE THREAD

**Issue by Dome-World** [venera-app/venera#75]
### Description

网页端下面的才是原本子标题，上面是通过二次翻译过来的英文标题，几乎没人会看懂，应当采用下面的

![Screenshot_2024-11-26-14-45-38-790_com android browser](https://github.com/user-attachments/assets/a97c5813-1680-4b57-9fc9-f85927d3cd03)
![Screenshot_2024-11-26-14-51-23-478_com android browser](https://github.com/user-attachments/assets/a53471f8-39c8-4b55-88ec-b2a1e6c01cb7)

### Version

1.0.7

### Operating system

Android

**Comment by wgh136** [comment]
发错地方了
