### ISSUE TITLE
漫画本地导入支持zip格式

### ISSUE THREAD

**Issue by nief12** [venera-app/venera#76]
### Description

e站的种子下载下来是zip格式，要是可以支持zip就比较好，感谢大佬

### Operating System

Android

### picture

**Comment by wgh136** [comment]
你把zip后缀改成cbz就可以导了

**Comment by nief12** [comment]
确实可以，但是如果漫画太多了的话，就需要改后缀脚本，当然这个需求可能不大，大佬你酌情考虑就好> 你把zip后缀改成cbz就可以导了

**Comment by nief12** [comment]
> 你把zip后缀改成cbz就可以导了
确实可以，但是如果漫画太多了的话，就需要改后缀脚本，当然这个需求可能不大，大佬你酌情考虑就好

**Comment by nief12** [comment]
> 你把zip后缀改成cbz就可以导了

确实可以，但是如果漫画太多了的话，就需要改后缀脚本，当然这个需求可能不大，大佬你酌情考虑就好
