### ISSUE TITLE
[Bug]: Mac端无法使用

### ISSUE THREAD

**Issue by HarmonyTou** [venera-app/venera#78]
### Description

如题

### Version

v1.0.7

### Operating system

macOS

### logs

_LSOpenURLsWithCompletionHandler() failed with error -10810

### Screenshot or video

![image](https://github.com/user-attachments/assets/df0505de-a3b1-4699-81de-b0bec2aefaa2)
![image](https://github.com/user-attachments/assets/74cc8467-13f0-4665-a521-b7fd8204153d)

**Comment by deltamaya** [comment]
我的M3 Air上没有问题, 你可以提供更多信息吗

**Comment by HarmonyTou** [comment]
> 我的M3 Air上没有问题, 你可以提供更多信息吗

我使用的是国行M4 Pro，还有其它可以提供的吗？

**Comment by deltamaya** [comment]
可以先尝试重新安装一下， 如果不行请提供系统信息和Console下的Crash Report

**Comment by HarmonyTou** [comment]
> 可以先尝试重新安装一下， 如果不行请提供系统信息和Console下的Crash Report

重装两次解决了，能运行了，非常感谢！
