### ISSUE TITLE
本地漫画观看可以预加载几张图片

### ISSUE THREAD

**Issue by nief12** [venera-app/venera#91]
### Description

对于本地导入的漫画，每观看一页就要转一个圈，特别是比较大和画质高的，而且很奇怪的是，本地漫画如果导入时勾选移到app的目录下，我也看到了文件是和app下载的内容是放在一个文件夹的，但app下载的不用加载，但本地导入的需要，按理说导入了的已经解压过了，应该能直接读取的，不知道是不是读取到的是未解压源文件

### Operating System

Android

**Comment by wgh136** [comment]
@nief12 本地导入的漫画一般都是分辨率很高的, app内下载的大概率是压缩的. 高分辨率的图片解码后占用的内存空间很大, 可能几张图片就达到了允许的缓存上线.
要解决这个问题, 一方面限制解码图片的分辨率上线, 另一方面提高允许的缓存上限.
为了使这个缓存上限合理, 需要加入检测可用内存的大小机制, 但是试了一下, 目前pub上的检测内存的包有问题且很久没维护了. 有点麻烦, 工作量会有点大

**Comment by nief12** [comment]
> @nief12 本地导入的漫画一般都是分辨率很高的, app内下载的大概率是压缩的. 高分辨率的图片解码后占用的内存空间很大, 可能几张图片就达到了允许的缓存上线.
> 要解决这个问题, 一方面限制解码图片的分辨率上线, 另一方面提高允许的缓存上限.
> 为了使这个缓存上限合理, 需要加入检测可用内存的大小机制, 但是试了一下, 目前pub上的检测内存的包有问题且很久没维护了. 有点麻烦, 工作量会有点大

其实感觉可以测验一下只缓存一张高分辨率的内存会不会达到上限就可以了，因为正常就算不预加载，转圈时间也很短可能一秒都没有，只是影响观看体验而已，如果只预加载一张应该也是够用了的，现在项目刚起步，这方面的需求优先级也不是很高，太费力气反而会不好
