### ISSUE TITLE
本地漫画无法阅读，并且貌似内存溢出了

### ISSUE THREAD

**Issue by nief12** [venera-app/venera#95]
### Description

![Screenshot_20241212_224342_com_github_wgh136_venera_MainActivity](https://github.com/user-attachments/assets/f3fd2a40-c455-4abd-96c0-7094fa2ede4f)
![Screenshot_20241212_224319_com_github_wgh136_venera_MainActivity](https://github.com/user-attachments/assets/2a9c1cad-3c18-46bc-9eed-60e63868113f)
如上图
我看的是下面的种子链接
magnet:?xt=urn:btih:257d815980213bd9e6647ee1048e506f6a6ac35b&dn=[パイレーツキャット] 立ちんぼしていた地雷系ちゃんが罠にかかっちゃうお話 [中国翻訳] [白杨汉化组].zip

### Version

v1.1.0

### Operating system

Android

### logs

Null check operator used on a null value
#0      _createImageProviderFromKey (package:venera/pages/reader/images.dart:654)
#1      _GalleryModeState.cache (package:venera/pages/reader/images.dart:138)
#2      _GalleryModeState.build.<anonymous closure> (package:venera/pages/reader/images.dart:171)
#3      _PhotoViewGalleryState._buildPageOption (package:photo_view/photo_view_gallery.dart:318)
#4      _PhotoViewGalleryState._buildItem (package:photo_view/photo_view_gallery.dart:251)
#5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:497)
#6      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:953)
#7      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:967)
#8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038)
#9      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:959)
#10     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:367)
#11     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2738)
#12     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1108)
#13     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2738)
#14     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:356)
#15     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:442)
#16     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:319)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#18     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:124)
#19     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:164)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#21     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:609)
#22     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1524)
#23     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1435)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:117)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2627)...

**Comment by wgh136** [comment]
为什么你认为内存溢出了

**Comment by nief12** [comment]
> 为什么你认为内存溢出了

我不太擅长flutter抱歉。。我之前遇到界面错乱涂抹，有人和我说是内存溢出导致的。。

**Comment by wgh136** [comment]
应该是字体问题
