### ISSUE TITLE
[Need Help]上架到AUR仓库

### ISSUE THREAD

**Issue by Shapaper233** [venera-app/venera#99]
### Content

https://aur.archlinux.org/
希望有大佬能出手将该软件上架到aur仓库
滚动更新的时候可以一起滚，防止有时旧版本加载不出改版后的网站的图片

**Comment by Lilinzta** [comment]
https://aur.archlinux.org/packages/venera-bin

**Comment by Shapaper233** [comment]
> https://aur.archlinux.org/packages/venera-bin

谢谢
